# Generated by Django 4.0.3 on 2022-03-24 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_serviceprovider'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Customer',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
    ]
